import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    absolute: '', // * It is completely ignored rest all the way through
    default: 'My Next 14 Features', // * this is the fallback for the default title
    template: '%s Blog Post', // * This is the pipe character as the suffix
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="flex flex-auto items-center justify-center cursor-pointer">
              <li className='m-5'>
                <Link href={'/'}>Home</Link>
              </li>
              <li className='m-5'>
                <Link href={'/pages/login'}>Auth</Link>
              </li>
              <li className='m-5'>
                <Link href={'/pages/order-product'}>Order Product</Link>
              </li>
              <li className='m-5'>Old</li>
              <li className='m-5'>Contact</li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
